### ISSUE TITLE
Migrate ElixirFocus content and delete that site

### ISSUE THREAD

**Issue by zorn** [zorn/mikezornek.com#33]
## TODOS

- [x] Search for hard links to https://elixirfocus.com and replace (and phoenixbyexample?)
- [x] make sure no tags are being used
- [x] delete the ~~AWS~~ GitHub Pages site.
